# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.sealed_secrets.v1alpha1 import SealedSecret as _Resource0

_MODELS = {
    ("SealedSecret", "bitnami.com/v1alpha1"): (
        "cloudcoil.models.sealed_secrets.v1alpha1",
        "SealedSecret",
    ),
    ("SealedSecret", ""): ("cloudcoil.models.sealed_secrets.v1alpha1", "SealedSecret"),
}


@overload
def get_model(
    kind: Literal["SealedSecret"], *, api_version: Literal["bitnami.com/v1alpha1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["SealedSecret"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
