# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import AwareDatetime, Base64Str, ConfigDict, Field


class SealedSecretSpecTemplateMetadata(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SealedSecretSpecTemplateMetadata"]:
            return SealedSecretSpecTemplateMetadata

        def build(self) -> "SealedSecretSpecTemplateMetadata":
            return SealedSecretSpecTemplateMetadata(**self._attrs)

        def annotations(self, value: dict[str, str] | None, /) -> Self:
            return self._set("annotations", value)

        def finalizers(self, value: list[str] | None, /) -> Self:
            return self._set("finalizers", value)

        def labels(self, value: dict[str, str] | None, /) -> Self:
            return self._set("labels", value)

        def name(self, value: str | None, /) -> Self:
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            return self._set("namespace", value)

    class BuilderContext(BuilderContextBase["SealedSecretSpecTemplateMetadata.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SealedSecretSpecTemplateMetadata.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SealedSecretSpecTemplateMetadata."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["SealedSecretSpecTemplateMetadata", Builder]:
        return GenericListBuilder[
            SealedSecretSpecTemplateMetadata, SealedSecretSpecTemplateMetadata.Builder
        ]()

    model_config = ConfigDict(
        extra="allow",
    )
    annotations: dict[str, str] | None = None
    finalizers: list[str] | None = None
    labels: dict[str, str] | None = None
    name: str | None = None
    namespace: str | None = None


class SealedSecretStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SealedSecretStatusConditionsItem"]:
            return SealedSecretStatusConditionsItem

        def build(self) -> "SealedSecretStatusConditionsItem":
            return SealedSecretStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: AwareDatetime | None, /) -> Self:
            "Last time the condition transitioned from one status to another."
            return self._set("last_transition_time", value)

        def last_update_time(self, value: AwareDatetime | None, /) -> Self:
            "The last time this condition was updated."
            return self._set("last_update_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def status(self, value: str, /) -> Self:
            'Status of the condition for a sealed secret.\nValid values for "Synced": "True", "False", or "Unknown".'
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            'Type of condition for a sealed secret.\nValid value: "Synced"'
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["SealedSecretStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SealedSecretStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SealedSecretStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["SealedSecretStatusConditionsItem", Builder]:
        return GenericListBuilder[
            SealedSecretStatusConditionsItem, SealedSecretStatusConditionsItem.Builder
        ]()

    last_transition_time: Annotated[AwareDatetime | None, Field(alias="lastTransitionTime")] = None
    "Last time the condition transitioned from one status to another."
    last_update_time: Annotated[AwareDatetime | None, Field(alias="lastUpdateTime")] = None
    "The last time this condition was updated."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    status: str
    'Status of the condition for a sealed secret.\nValid values for "Synced": "True", "False", or "Unknown".'
    type: str
    'Type of condition for a sealed secret.\nValid value: "Synced"'


class SealedSecretStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SealedSecretStatus"]:
            return SealedSecretStatus

        def build(self) -> "SealedSecretStatus":
            return SealedSecretStatus(**self._attrs)

        @overload
        def conditions(
            self, value_or_callback: list[SealedSecretStatusConditionsItem] | None, /
        ) -> "SealedSecretStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        SealedSecretStatusConditionsItem,
                        SealedSecretStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    SealedSecretStatusConditionsItem,
                    SealedSecretStatusConditionsItem.Builder,
                ]
                | list[SealedSecretStatusConditionsItem],
            ],
            /,
        ) -> "SealedSecretStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[SealedSecretStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Represents the latest available observations of a sealed secret\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[SealedSecretStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SealedSecretStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration reflects the generation most recently observed by the sealed-secrets controller."
            return self._set("observed_generation", value)

    class BuilderContext(BuilderContextBase["SealedSecretStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SealedSecretStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SealedSecretStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SealedSecretStatus", Builder]:
        return GenericListBuilder[SealedSecretStatus, SealedSecretStatus.Builder]()

    conditions: list[SealedSecretStatusConditionsItem] | None = None
    "Represents the latest available observations of a sealed secret\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration reflects the generation most recently observed by the sealed-secrets controller."


class SealedSecretSpecTemplate(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SealedSecretSpecTemplate"]:
            return SealedSecretSpecTemplate

        def build(self) -> "SealedSecretSpecTemplate":
            return SealedSecretSpecTemplate(**self._attrs)

        def data(self, value: dict[str, Any] | None, /) -> Self:
            "Keys that should be templated using decrypted data."
            return self._set("data", value)

        def immutable(self, value: bool | None, /) -> Self:
            "Immutable, if set to true, ensures that data stored in the Secret cannot\nbe updated (only object metadata can be modified).\nIf not set to true, the field can be modified at any time.\nDefaulted to nil."
            return self._set("immutable", value)

        @overload
        def metadata(
            self, value_or_callback: SealedSecretSpecTemplateMetadata | None, /
        ) -> "SealedSecretSpecTemplate.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[
                [SealedSecretSpecTemplateMetadata | None.Builder],
                SealedSecretSpecTemplateMetadata
                | None.Builder
                | SealedSecretSpecTemplateMetadata
                | None,
            ],
            /,
        ) -> "SealedSecretSpecTemplate.Builder": ...

        @overload
        def metadata(
            self, value_or_callback: Never = ...
        ) -> "SealedSecretSpecTemplateMetadata | None.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            "Standard object\u0027s metadata.\nMore info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
            if self._in_context and value_or_callback is UNSET:
                context = SealedSecretSpecTemplateMetadata | None.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SealedSecretSpecTemplateMetadata | None.builder())
                if isinstance(output, SealedSecretSpecTemplateMetadata | None.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        def type(self, value: str | None, /) -> Self:
            "Used to facilitate programmatic handling of secret data."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["SealedSecretSpecTemplate.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SealedSecretSpecTemplate.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SealedSecretSpecTemplate."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SealedSecretSpecTemplate", Builder]:
        return GenericListBuilder[SealedSecretSpecTemplate, SealedSecretSpecTemplate.Builder]()

    data: dict[str, Any] | None = None
    "Keys that should be templated using decrypted data."
    immutable: bool | None = None
    "Immutable, if set to true, ensures that data stored in the Secret cannot\nbe updated (only object metadata can be modified).\nIf not set to true, the field can be modified at any time.\nDefaulted to nil."
    metadata: SealedSecretSpecTemplateMetadata | None = None
    "Standard object\u0027s metadata.\nMore info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
    type: str | None = None
    "Used to facilitate programmatic handling of secret data."


class SealedSecretSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SealedSecretSpec"]:
            return SealedSecretSpec

        def build(self) -> "SealedSecretSpec":
            return SealedSecretSpec(**self._attrs)

        def data(self, value: Base64Str | None, /) -> Self:
            "Data is deprecated and will be removed eventually. Use per-value EncryptedData instead."
            return self._set("data", value)

        def encrypted_data(self, value: dict[str, str], /) -> Self:
            return self._set("encrypted_data", value)

        @overload
        def template(
            self, value_or_callback: SealedSecretSpecTemplate | None, /
        ) -> "SealedSecretSpec.Builder": ...

        @overload
        def template(
            self,
            value_or_callback: Callable[
                [SealedSecretSpecTemplate.Builder],
                SealedSecretSpecTemplate.Builder | SealedSecretSpecTemplate,
            ],
            /,
        ) -> "SealedSecretSpec.Builder": ...

        @overload
        def template(
            self, value_or_callback: Never = ...
        ) -> "SealedSecretSpecTemplate.BuilderContext": ...

        def template(self, value_or_callback=UNSET, /):
            "Template defines the structure of the Secret that will be\ncreated from this sealed secret."
            if self._in_context and value_or_callback is UNSET:
                context = SealedSecretSpecTemplate.BuilderContext()
                context._parent_builder = self
                context._field_name = "template"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SealedSecretSpecTemplate.builder())
                if isinstance(output, SealedSecretSpecTemplate.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("template", value)

    class BuilderContext(BuilderContextBase["SealedSecretSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SealedSecretSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SealedSecretSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SealedSecretSpec", Builder]:
        return GenericListBuilder[SealedSecretSpec, SealedSecretSpec.Builder]()

    data: Base64Str | None = None
    "Data is deprecated and will be removed eventually. Use per-value EncryptedData instead."
    encrypted_data: Annotated[dict[str, str], Field(alias="encryptedData")]
    template: SealedSecretSpecTemplate | None = None
    "Template defines the structure of the Secret that will be\ncreated from this sealed secret."


class SealedSecret(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "sealedsecrets",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["SealedSecret"]:
            return SealedSecret

        def build(self) -> "SealedSecret":
            return SealedSecret(**self._attrs)

        def api_version(self, value: Literal["bitnami.com/v1alpha1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["SealedSecret"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "SealedSecret.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "SealedSecret.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: SealedSecretSpec, /) -> "SealedSecret.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [SealedSecretSpec.Builder], SealedSecretSpec.Builder | SealedSecretSpec
            ],
            /,
        ) -> "SealedSecret.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "SealedSecretSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = SealedSecretSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SealedSecretSpec.builder())
                if isinstance(output, SealedSecretSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: SealedSecretStatus | None, /
        ) -> "SealedSecret.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [SealedSecretStatus.Builder],
                SealedSecretStatus.Builder | SealedSecretStatus,
            ],
            /,
        ) -> "SealedSecret.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "SealedSecretStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = SealedSecretStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(SealedSecretStatus.builder())
                if isinstance(output, SealedSecretStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["SealedSecret.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = SealedSecret.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for SealedSecret."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["SealedSecret", Builder]:
        return GenericListBuilder[SealedSecret, SealedSecret.Builder]()

    api_version: Annotated[Literal["bitnami.com/v1alpha1"], Field(alias="apiVersion")] = (
        "bitnami.com/v1alpha1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["SealedSecret"] = "SealedSecret"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: SealedSecretSpec
    status: SealedSecretStatus | None = None
